### ISSUE TITLE
Play area and return behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#117]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
The atoms floating back from being off screen seem to return to the play area. In other sims it seems like they would normally return to their buckets. Also, the area where this return is triggered is shockingly small.

**Visuals**
![area](https://user-images.githubusercontent.com/41024075/69450049-7b2b4c00-0d19-11ea-92f3-4e6653793feb.png)
![returntoplay](https://user-images.githubusercontent.com/41024075/69450055-7d8da600-0d19-11ea-9794-0130abec6244.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Looks like this matches the Java behavior. That said, this approach generally feels weird to me. 

There is no reason to allow users to drag the atoms beyond the top or left side of the ?dev boundary. Similarly, there is no reason to allow atoms to be dragged below the carousel. The right side of the screen is a little trickier since we need to allow molecules to be dragged into the collection area.

Here's what I propose
* Do not let atoms be dragged outside of the green box. The left, top, and right bounds match dev, and the bottom bound is flush with the bottom of the carousel.
* If an atom or molecule is released to the right of the red dashed line and does not correspond to a matching molecule/collection, animate the return back into the play area.
* If an atom or molecule is dragged into the navy box, return the atom(s) it the corresponding bucket(s).
![image](https://user-images.githubusercontent.com/8419308/69577515-bb920080-0f8b-11ea-8d50-44bcdd82ef9a.png)

**Comment by Denz1994** [comment]
The bounds have been updated to match the mockup from above. 

Note the 3rd screen uses different bounds for the carousel. It would really work out nicely (due to the above change) if the refill button could be moved to the right side of the screen. The top of the refill button would be aligned with the top of the carousel. See the mockup below.

![image](https://user-images.githubusercontent.com/13894380/70651941-c1d8db80-1c1f-11ea-89ee-e35e27e0ff4a.png)

We could also align the reset button by moving it up a bit and centering it with the refill button. This may also work out better if we iconize the refill button so i18n for the text wouldn't be a problem in that smaller space.

@arouinfar Can your review this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.29/phet/) for the bound changes? Also, what are your thoughts about moving the refill button?

**Comment by arouinfar** [comment]
@Denz1994 the boundaries in dev.29 are generally looking pretty good, but things are a little funky on the 3rd screen.

This atom will get pushed into the play area.
<img width="122" alt="Screen Shot 2019-12-11 at 2 20 43 PM" src="https://user-images.githubusercontent.com/8419308/70661499-a969c080-1c21-11ea-8482-335a84d2b281.png">

This atom will get returned to the carousel.
<img width="123" alt="Screen Shot 2019-12-11 at 2 20 36 PM" src="https://user-images.githubusercontent.com/8419308/70661500-a969c080-1c21-11ea-8125-e74ed8dc699d.png">

Let's simplify things a bit further on the 3rd screen, and consider just two regions. If the atom is released below the magneta line (aligned to top of carousel) the atom will return to the carousel. 
![image](https://user-images.githubusercontent.com/8419308/70661976-97d4e880-1c22-11ea-891f-009f4dd1a308.png)

Another thing I've noticed is that the animation to bump the atom back into the play area feels really slow. Can we speed it up a bit @Denz1994?

> We could also align the reset button by moving it up a bit and centering it with the refill button.

The refill button is being discussed in #58, and in design meeting, we had entertained the idea of layering the button on top of the carousel. We can discuss the button placement in that issue.

**Comment by Denz1994** [comment]
Hey @arouinfar can you check this[ dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.33/phet/build-a-molecule_en_phet.html) for the bounds on the 3rd screen?

**Comment by arouinfar** [comment]
@Denz1994 the boundaries are all looking good, but the animation speed when bumping the atom back into the play area feels slower than it needs to be. Can you speed it up?

**Comment by Denz1994** [comment]
Could you take a look at master @arouinfar? I doubled the speed.

**Comment by arouinfar** [comment]
Looks much better, thanks @Denz1994

**Comment by Denz1994** [comment]
Closing this one. The latest dev version contains these changes.
