### ISSUE TITLE
Unable to build Butane on screen 3

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/build-a-molecule#170]
I tried to build Butane - which is possible given the atoms - but for some reason it doesn't seem to allow it. Can you look at the database to see that it is included? And if not figure out why, or if it is, why I can't build it? Thanks! Also assigning JO, since you both worked on the database together.

**Comment by Denz1994** [comment]
In the database, the entry is currently listed as `n-butane C4H10`. In this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.65/phet/build-a-molecule_en_phet.html), I was able to build `n-Butane | C4H10` on the 3rd screen due to recent changes in https://github.com/phetsims/build-a-molecule/issues/148. 

![image](https://user-images.githubusercontent.com/13894380/78067415-b17e7500-7364-11ea-9410-a102497cf659.png)

In https://github.com/phetsims/build-a-molecule/issues/153#issuecomment-580072157, we decided to use `C4H10` for `n-Butane` referencing the PubChem entry [here](https://github.com/phetsims/build-a-molecule/issues/153#issuecomment-580072157) where `n-Butane` is listed as a synonym for `Butane`. 

@arouinfar Should we rename the entry `n-Butane` to `Butane`? I don't know what would be the more commonly accepted name, despite both being the same in PubChem.

**Comment by kathy-phet** [comment]
If you can build it now, we should replace the current public version. Thanks, Kathy. I am not concerned about the name, just could not even build it. Please post the new version. Thanks!

Sent from my iPhone

On Mar 31, 2020, at 1:36 PM, Denzell Barnett <notifications@github.com> wrote:

﻿

In the database, the entry is currently listed as n-butane C4H10. In this dev version<https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.65/phet/build-a-molecule_en_phet.html>, I was able to build n-Butane | C4H10 on the 3rd screen due to recent changes in #148<https://github.com/phetsims/build-a-molecule/issues/148>.

[image]<https://user-images.githubusercontent.com/13894380/78067415-b17e7500-7364-11ea-9410-a102497cf659.png>

In #153 (comment)<https://github.com/phetsims/build-a-molecule/issues/153#issuecomment-580072157>, we decided to use C4H10 for n-Butane referencing the PubChem entry here<https://github.com/phetsims/build-a-molecule/issues/153#issuecomment-580072157> where n-Butane is listed as a synonym for Butane.

@arouinfar<https://github.com/arouinfar> Should we rename the entry n-Butane to Butane? I don't know what would be the more commonly accepted name, despite both being the same in PubChem.

**Comment by Denz1994** [comment]
Got it I'll follow up with @mattpen to post a new version.

**Comment by Denz1994** [comment]
Thanks for the explanation @arouinfar. This change was included in the dev version in this comment. I'll close this issue.
