### ISSUE TITLE
Tolerance on bump-away vs connect

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/build-a-molecule#171]
@arouinfar - When I was playing with the posted prototype version, it seemed like the tolerance on creating a bond was pretty small. I had to be more precise about placement then I expected. It seems like the usability would be improved by lowering the tolerance, so if you are a bit overlapping an atom and drop say a H, it will attach at the nearby open spot if it is an allowed attachment spot. 

Can you take a look at this and see what you think?

**Comment by arouinfar** [comment]
@kathy-phet there was a lot of back-and-forth with this in #154. Initially the threshold distance for atoms to bond was so large that atoms cut off of a molecule would automatically reconnect to the molecule when clicked.

I think the underlying issue here is that atoms will repel each other if the approach is diagonal. This behavior is different from Java. 
![javaDiagonal](https://user-images.githubusercontent.com/8419308/78081562-0f638a80-736e-11ea-9de3-50d3c07aaa56.gif)

@Denz1994 can you take a look?

**Comment by kathy-phet** [comment]
Yes, it is related to this, but also to the fact that it doesn't "jump to the nearest allowable position". 

This is what the current HTML behavior is: 
![BAM_html_atomsdoesnotstick](https://user-images.githubusercontent.com/5096804/78085797-34a9c600-7379-11ea-9e98-22928b02de60.gif)

This is what the old Java sim did: 
![BAM_Java_atomsticks](https://user-images.githubusercontent.com/5096804/78085802-3c696a80-7379-11ea-86b9-61bf21f5f3b7.gif)

It makes it very usable for it to jump to the nearest open position that will work when it is overlapping the atom you are trying to add it too.

**Comment by kathy-phet** [comment]
@Denz1994 - Can you take a look at this issue? It would really help the usability of the sim to address this in the short term if possible. Perhaps we can have a shortish meeting tomorrow during design time (@arouinfar)?

**Comment by Denz1994** [comment]
`Kit.bondDistanceThreshold` determines how far from the bonding position an atom has to be before bonding. Along with this, `Kit.attemptToBondMolecule()` would need to proceed with bonding if `atomA.destinationBounds.intersectsBounds( atomB.destinationBounds ) === true`. After checking if the atoms are within the bonding threshold we can check if their bounds are overlapping. 

The best location is already determined by `BondOption` so I think an additional conditional is the only thing required here.

**Comment by kathy-phet** [comment]
@Denz1994 - I think it might be preferable UI to first check if atoms are overlapping and if so "always bond to the closest bond", and only use Distance Threshold if the atoms are not overlapping. That way DistanceThreshold only applies for atoms that are physically separated.

**Comment by Denz1994** [comment]
This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.67/phet/build-a-molecule_en_phet.html) will bond overlapping atoms to the atom's nearest bonding option (North, South, East, or West).

(Re diagonal bonding) Because we are now considering the bounds of the full atom, the threshold for diagonal bonding is a bit more lenient in the diagonal directions. This is because the bounds are essentially a rectangle around the circular atom, so a diagonal approach for bonding will intersect bonds at the edge of the bounding rectangle. 

@arouinfar Could you please review the above [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.67/phet/build-a-molecule_en_phet.html) and make sure this doesn't conflict with atoms being bonded too easily as mentioned here https://github.com/phetsims/build-a-molecule/issues/154#issuecomment-588516817.

**Comment by arouinfar** [comment]
Thanks @Denz1994, I was just reading through this issue, and I thought the proposals all sounded good. Excited to test it out!

**Comment by mattpen** [comment]
https://phet.colorado.edu/sims/html/build-a-molecule/latest/build-a-molecule_en.html is now available.

**Comment by Denz1994** [comment]
@arouinfar Mentioned via slack, that she will write up a slight improvement. I'll remove the high-priority label because this is currently available as mentioned above.

**Comment by Denz1994** [comment]
While meeting with @arouinfar, she mentioned that sometimes the molecules bump away when they are diagonally near another molecule. Molecules are bumped away when they are not within the range to bond (kit.bondDistanceThreshold) but are still overlapping the padded molecule bounds (kit.interMoleculePadding). Because the java version had this same behavior, we decided to only slightly increase the separation distance and bonding threshold so the separation looks more intentional.

This separation also handles cases like the image below. Here the H2 separates further than expected from the larger molecule, so the molecule buttons and name don't overlap each other. The topmost blue-button belongs to the larger molecule.
![image](https://user-images.githubusercontent.com/13894380/79475671-fe558300-7fd5-11ea-8c08-d35dad677f5d.png)

This [dev version ](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.67/phet/build-a-molecule_en_phet.html) has these changes  @kathy-phet and @arouinfar.

**Comment by arouinfar** [comment]
@Denz1994 I think the bonding behavior is looking pretty good, but @kathy-phet should also take it for a spin.

**Comment by Denz1994** [comment]
Latest on this issue: @kathy-phet just needs to look at over the latest [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.79/phet/build-a-molecule_all_phet.html) to sign off on the bonding distance and separation distance.

Raising priority on this issue because we are getting close to an RC.

**Comment by ariel-phet** [comment]
I think I feel comfortable "signing off" for @kathy-phet in this case. The behavior feels very natural and seamless to me currently in dev.79

Closing.

**Comment by kathy-phet** [comment]
Just for the record, it does feel good to me too!
