### ISSUE TITLE
Overlapping hydrogen or others

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#190]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/506.
I noticed that, when atoms would need to be in the same spot, though linked to different atoms, the sim does not allow this. However, with hydrogen atoms it is allowed and this causes an overlap of the atoms. This can also occur to an extent with very large atoms that are placed next to each other. This may likely be the best solution. If so, please close.

**Visuals**
![butcanoverlap](https://user-images.githubusercontent.com/41024075/84185134-c0ac2e00-aa4b-11ea-987f-9c0d3bcf1bf4.png)
![overlappingP](https://user-images.githubusercontent.com/41024075/84185145-c6097880-aa4b-11ea-9c62-5439886a9956.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.75/phet/build-a-molecule_all_phet.html
Version: 1.0.0-dev.75 2020-06-01 13:20:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
I would vote to pass on fixing this one. There would most likely be an intrusive patch to the model that determines bonding locations based on molecules that aren't neighbors to an atom. For instance, the bottom-most Phosphorus isn't aware of the position/bounds of the uppermost Phosphorus. The bottom-most Phosphorus only knows about its neighbor, bottom-most carbon.

Also note, this is present in the java version and I don't think it was reported as an issue.
![image](https://user-images.githubusercontent.com/13894380/84213214-11dd1180-aa8e-11ea-96cc-74a673ab9360.png)

I'll leave to @arouinfar to decide. Raising priority because this will require model changes.

**Comment by arouinfar** [comment]
Thanks for reporting @KatieWoe. I agree with @Denz1994's decision to leave this as-is.
