### ISSUE TITLE
Check for listener leaks

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#38]
Dragging atoms after slicing seems to be too slow.

**Comment by Denz1994** [comment]
The listeners that were implemented at the time this issue was created have been removed. DragListeners have been implemented instead. These listeners are now being added and removed at disposal.

Also, this sim has gone through two dev cycles and dragging was reported as being laggy or slow. Closing this issue and any further leaks will be handled in #115.
