### ISSUE TITLE
User suggestion: glucose molecule

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-a-molecule#79]
> Also, if you accept unsolicited feedback, we love to have a glucose molecule in the simulation for students to build.

Assigning to @emily-phet for review.

**Comment by emily-phet** [comment]
@oliver-phet - we considered this during the initial development. To include glucose, we would need to have a screen in the "Larger Molecules" tab that includes a bucket with 6 carbons, and at least 12 hydrogens and 6 oxygens. Each increase in the number of carbons increases (probably exponentially) the total number of molecules that would need to be able to be built in the sim. We decided to limit the number of carbons to 4 - which makes the total number of molecules allowed in the sim about 5,000 (I believe). Limiting the number of carbons to 4 also minimizes the issues that you run into with nonlinear molecules...so we don't have to deal with distinguishing when people are trying to build chains, rings, or chains with rings on them (very hard to do since we don't explicitly include bonding types in the sim). 
Does that help address this issue?

**Comment by oliver-phet** [comment]
Yep, thanks for the explanation. I will reply to the user!
