### ISSUE TITLE
Cannot read property 'isSuppliedAndEnabled' of undefined

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-a-molecule#81]
Press the close button in a 3D view.

```
Uncaught TypeError: Cannot read property 'isSuppliedAndEnabled' of undefined
    at CloseButton.startEvent (PhetioObject.js?bust=1517418166103:106)
    at PushButtonModel.fire (PushButtonModel.js?bust=1517418166103:150)
    at Array.<anonymous> (PushButtonModel.js?bust=1517418166103:83)
    at Emitter.emit2 (Emitter.js?bust=1517418166103:177)
    at Property._notifyListeners (Property.js?bust=1517418166103:188)
    at Property._setAndNotifyListeners (Property.js?bust=1517418166103:175)
    at Property.set (Property.js?bust=1517418166103:122)
    at Object.up (ButtonListener.js?bust=1517418166103:49)
    at ButtonListener.buttonUp (DownUpListener.js?bust=1517418166103:129)
    at Object.up (DownUpListener.js?bust=1517418166103:62)
```

**Comment by jonathanolson** [comment]
Does PushButtonModel need to call initializePhetioObject on its phetioEventSource? (I briefly looked into this, but couldn't determine what the problem was immediately).

**Comment by samreid** [comment]
I added a fix that gets it working again, but the fix is unsatisfactory because it *seems* unrelated to the problem.  The problem is that PhetioObject can be configured from a sub-constructor or a sub-mutate call, and it uses options detection to decide which.  By adding the Tandem to the mutate call options, it triggered it to know which to use (and finish its initialization).  Not sure if we should try to address this somehow or close issue and move on.  @pixelzoom can you please advise?

**Comment by pixelzoom** [comment]
@samreid said:
> I added a fix that gets it working again, but the fix is unsatisfactory because it seems unrelated to the problem.

Agreed, unsatisfactory.

If `phetioEventSource` is a part of PhET-iO that must be initialized, then it should be included in PhetioObject `DEFAULTS`.   And documented there as well, since it's currently not documented anywhere else.

I’m also not convinced of (or perhaps don’t understand) the need for `phetioEventSource`.  It appears to be only used (needed?) for buttons, and involves creating a sort of proxy PhetioObject instance.   

Relevant Slack discussion 2/5/18:

```
Sam Reid [10:55 AM]
When one object wants to “route” events through a particular PhetioObject, it uses `phetioEventSource` to do so.

Chris Malley [10:55 AM]
Why does it only appear in buttons?

Sam Reid [10:56 AM]
Because we wanted the events to appear as if they are coming from the button itself, not an “implementation detail” related input listener/button handler class.

Chris Malley [10:56 AM]
Where is `phetioEventSource` documented?


Sam Reid [10:58 AM]
I don’t see any reasonable documentation in the source code.  There may be issues about it, but I haven’t found them yet.

Here are some related issues: https://github.com/phetsims/phet-io/issues?utf8=%E2%9C%93&q=is%3Aissue+eventSource

It looks like it was previously called `eventSource`

Where should we document `phetioEventSource`?  Should the documentation contain more than my explanation above?


Chris Malley [11:12 AM]
Rather than the workaround applied for https://github.com/phetsims/build-a-molecule/issues/81, I was going to suggest including `phetioEventSource` in PhetioObject `DEFAULTS`.  If you think that’s appropriate, it would be documented there. (edited)

I’m also not convinced of (or perhaps don’t understand) the need for `phetioEventSource`.  It appears to be only used (needed?) for buttons, and involves creating a sort of proxy PhetioObject instance. (edited)
```

**Comment by samreid** [comment]
`phetioEventSource` is used to send messages from a particular (other) object.  For instance, we would like the data stream to read like:

> resetAllButton pressed

However, PushButtonModel actually handles the user input and fires the event, but we do not want the event stream to read like:

> resetAllButton.buttonModel pressed

From PhET-iO's perspective, the PushButtonModel is an implementation detail that should not leak into the API or event stream.  So instead we pass the PushButton to the PushButtonModel so the PushButtonModel can call `startEvent`/`endEvent` on it.  We cannot put the `phetioEventSource` in PhetioObject because types like PushButtonModel do not extend PhetioObject.

**Comment by pixelzoom** [comment]
You presumably have control over the tandem identifiers.  If `resetAllButton.buttonModel` is not desirable, why not just "flatten" the model/view distinction and have PushButtonModel use  `resetAllButton`?

**Comment by samreid** [comment]
Different objects cannot be assigned the same `phetioID`, hence `PushButtonModel` cannot use the same identifier as the `resetAllButton`.

**Comment by pixelzoom** [comment]
So how about adding `phetioEventSource` to PhetioObject `DEFAULTS`. Is that appropriate? Are there problems with doing that?

**Comment by samreid** [comment]
It seems inappropriate to add `phetioEventSource` to PhetioObject `DEFAULTS` because there are Objects that need to use `phetioEventSource` that are not `PhetioObject`s.

**Comment by pixelzoom** [comment]
@samreid Meet me on Slack to discuss when you have time.  I suspect that I have an incomplete/faulty understanding of why the reported assertion was occurring, and why https://github.com/phetsims/sun/commit/de39c347facfe4575a45bb8aec8493f6ce77ed2d resolved the assertion failure.

**Comment by pixelzoom** [comment]
Using `phetioEventSource` requires that a PhetioObject have `this.phetioObjectTandem`.  So rather than defining that in the default options for `NodesPushButton`, I think that  `this.phetioObjectTandem` should be assigned a default value in the constructor, prior to the `if` statement that calls `initializePhetioObject`.  I.e.:

```js
    // @public (read-only) - the unique tandem for this instance
    this.phetioObjectTandem = Tandem.optional;

    if ( options ) {
      this.initializePhetioObject( {}, options );
    }
```

**Comment by samreid** [comment]
To summarize, there were 2 problems.  NodesPushButton needed to send a `tandem` option, which was ultimately the resolution.  The second problem is documented here: https://github.com/phetsims/sun/issues/335
